<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NttBank.RagSearch.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation"/>
    <PackageReference Include="CorrelationId"/>
    <PackageReference Include="OllamaSharp"/>
    <PackageReference Include="Mapster.DependencyInjection"/>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>

    <PackageReference Include="EFCore.NamingConventions"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
    <PackageReference Include="Pgvector.EntityFrameworkCore"/>

    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore"/>

    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore"/>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting"/>
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/>
    <PackageReference Include="OpenTelemetry.Instrumentation.Http"/>
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime"/>
    <PackageReference Include="OpenTelemetry.Instrumentation.Process"/>
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore"/>
    <PackageReference Include="Npgsql.OpenTelemetry"/>

    <PackageReference Include="Serilog.AspNetCore"/>
    <PackageReference Include="Serilog.Settings.Configuration"/>
    <PackageReference Include="Serilog.Sinks.Async"/>
    <PackageReference Include="Serilog.Expressions"/>
    <PackageReference Include="Serilog.Sinks.Seq"/>
  </ItemGroup>

</Project>
